### ISSUE TITLE
Extension have stopped working with the latest Chrome

### ISSUE THREAD

**Issue by alexey-m-pavlov** [tsuliwaensis/New-Tabs-at-End-3000#4]
Hello! Unfortunately you extension seems to have stopped working recently with the latest Chrome. Could you be so kind to fix it?

**Comment by tsuliwaensis** [comment]
It doesn't seem broken to me. I am running Chrome 111.0.5563.146 on an Intel Mac.

**Comment by alexey-m-pavlov** [comment]
Hello!

Yes, it is working properly at the moment. I suppose it was some temporary
issue.

Anyway, thanks for the great extension and fast response!

ср, 29 мар. 2023 г. в 18:29, Tsuliwaënsis ***@***.***>:

> It doesn't seem broken to me. I am running Chrome 111.0.5563.146 on an
> Intel Mac.
>
-- 
Regards,
Alexey Pavlov

E-mail: ***@***.***
Phone: +7 913 975-83-76
